Models/Navigation - Copy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Casey_Leon.Models
{
    public class Class
    {
    }
}

Models/Navigation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Casey_Leon.Models
{
    public class Navigation
    {

        
        public int NavigationId { get; set; }

        public string NavigationUrl { get; set; }

        public string NavigationName { get; set; }
    }
}

Models/Portfolio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Casey_Leon.Models
{
    public class Portfolio
    {


        public int PortfolioId { get; set; }

        public string PortfolioUrl { get; set; }

        public string PortfolioName { get; set; }

        public string PortfolioPhoto { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using Microsoft.AspNetCore.Http;
//using Casey_Leon.Context;

namespace Casey_Leon.Controllers
{
  //  private LeonDb webAPIDataContext;
    public class HomeController : Controller
    {

        public HomeController()
        {
            //_webApiDataContext = _webApiDataContext;
            //webApiDataContext.Database.EnsureCreated();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Resume()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Portfolio()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }


        public IActionResult Error(HttpStatusCode statusCode)
        {
               
            ViewData["Message"] = statusCode;
            return View();
        }
    }
}

Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Casey_Leon.Controllers
{
    public class ProjectController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LIS3784_1()
        {
            return View();
        }
        public IActionResult LIS3784_2()
        {
            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@using System.Security
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="~/images/wtc.JPG" alt="Casey Hargarther" asp-append-version="true">
            <div class="caption">
                <h3>Casey Hargarther</h3>
                <p>Information Technology Professional</p>
                <p>
                    <a asp-area="" asp-controller="Home" asp-action="Resume" class="btn btn-primary btn-sm" role="button"><i class="fa fa-book"></i> Resume</a>
                    <a asp-area="" asp-controller="Home" asp-action="Portfolio" class="btn btn-primary btn-sm" role="button"><i class="fa fa-database"></i> Portfolio</a>
                    <a href="https://twitter.com/CaseyHargarther" class="btn btn-info btn-sm" role="button"><i class="fa fa-twitter"></i> Twitter</a>
                    <a href="http://www.linkedin.com/in/caseyhargarther" class="btn btn-info btn-sm" role="button"><i class="fa fa-linkedin-square"></i> LinkedIn</a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-7">
        <div class="jumbotron">
            <h1>Welcome </h1>
            <p class="lead">
                My name is Casey Hargarther. I am a recent graduate at Florida State University with a Bachelor's Degree in Information Technology. I am very passionate about what I do and I am very eager to succeed.
                The fields that specialize in are Web Development, Project Management, Technical Support, and Database Administration.
                This website shows examples of what I have accomplished during my tenure at Florida State University and beyond.
            </p>
        </div>
    </div>
</div>

Views/Home/Portfolio.cshtml
@{
    ViewBag.Title = "Portfolio";
}

<div class="row">
    <div class="col-md-8">
        <h2>@ViewBag.Title</h2>
    </div>
    <div class="col-md-4">
        <a href="#database" class="btn btn-info btn-lg"> <i class="fa fa-database"></i> Databases</a>
        &nbsp;
        <a href="#websites" class="btn btn-info btn-lg"> <i class="fa fa-globe"></i> Websites</a>
    </div><!-- /.col -->
</div><!-- /.row -->
<hr>
    <h2 id="websites"> <i class="fa fa-globe"></i> Web Development Portfolio</h2>
<hr />
    <div class="col-md-12">
        <!-- Waco Storage Units Pioneer Stor Lok -->
        <div class="row">
            <div class="col-md-10">
                <blockquote class="embedly-card" data-card-key="afcb7b48cdd541daa8387c35d318233a" data-card-controls="0" data-card-type="article-full"><h4><a href="https://www.wacostorageunits.com">Pioneer Stor & Lok - Waco, TX | Home</a></h4><p>Pioneer Stor and Lok is committed to provide affordable self-storage. This storage facility offers storage solutions for both your personal and business needs.</p></blockquote>
                <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
            </div>
        </div>


        <!-- GreenData -->
        <div class="row">

            <div class="col-md-10">
                <button type="button" class="btn btn-info pull-right btn-lg" data-toggle="modal" data-target="#greenData"> Learn More</button>

                <a class="embedly-card" href="http://casey.technology/LIS4381/P1">GreenData</a>
                <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>


            </div>
        </div>

        <!-- North Florida Home Inspections -->
        <div class="row">
            <div class="col-md-10">
                <button type="button" class="btn btn-info pull-right btn-lg" data-toggle="modal" data-target="#nfhi"> Learn More</button>
                <a class="embedly-card" href="http://casey.technology/LIS4381/P2">North Florida Home Inspections</a>
                <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>


            </div>

        </div>

        <!-- Places in Tallahassee -->
        <div class="row">
            <div class="col-md-10">
                <blockquote class="embedly-card" data-card-key="afcb7b48cdd541daa8387c35d318233a">
                    <h4><a href="http://www.placesintallahassee.com">Places in Tallahassee</a></h4>
                    <p>Whether you are a visitor, new student, transfer-student or a resident of Tallahassee or Leon County, there are a lot of things to do in Florida's Capitol City. This website was created to list the activities that anyone can do in Tallahassee.</p>
                </blockquote>
                <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
            </div>
        </div>
    </div>

    <!-- Rocket Products -->
    <!--   <div class="row">
                <div class="col-md-10">
               <blockquote class="embedly-card" data-card-key="afcb7b48cdd541daa8387c35d318233a"><h4><a href="http://rocket.caseyhargarther.com/info">Rocket Televisions</a></h4><p>Since the founding of Rocket Televisions in 2015, Rocket Televisions is a family owned and operated business that specializes in selling televisions to customers nationwide. Rocket Televisions only sells top of the line televisions that will satisfy you or we will refund you if you are not satisified with our products within a thirty day period.</p></blockquote>
    <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
    </div>
    </div>-->
    <div class="col-md-10">
        <p class="lead">
            <a class="embedly-card" href="http://casey.technology/LIS4381/A5">321 Game Review</a>
            <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
        </p>
    </div>
    <div class="row">
        <div class="col-md-10">
            <h2><i class="fa fa-code"></i> Website Contributions</h2>
        </div>
    </div>

<!-- Assignments Row LIS2780 -->
<div class="row">
    <hr>
    <h2 id="database"> <i class="fa fa-database"></i> Database Portfolio</h2>
    <h3> Database Concepts - Fall 2013 <small>Database Management</small></h3>

    <!-- /.row -->
    <hr>
    <!-- Projects Row LIS2780 -->
    <div class="row">

        <div class="col-md-5 portfolio-item">
            <div class="thumbnail">

                <a href="#">
                    <img class="img-rounded" src="~/images/LIS2780/P1_LIS2780.png" alt="P1" style="height:250px" asp-append-version="true" />
                </a>
                <h3>
                    <a href="#">Project One</a>
                </h3>

            </div>

        </div>
        <div class="col-md-5 col-md-offset-1 portfolio-item">
            <div class="thumbnail">

                <a href="#">
                    <img class="img-rounded" src="~/images/LIS2780/P2_LIS2780.png" alt="P2" style="height:250px" asp-append-version="true" />
                </a>
                <h3>
                    <a href="#">Project Two</a>
                </h3>

            </div>
        </div>



    </div>
    <!-- /.row -->
    <hr>
    <!-- Projects Row -->
    <h3>Information Organization and Communication - Fall 2014</h3>
    <div class="row">


        <div class="col-md-3 portfolio-item">
            <div class="thumbnail">
                <a href="#">
                    <img class="img-responsive" src="~/images/LIS3784/LIS3784_A2P.png" alt="A2 LIS3784" style="height:150px" asp-append-version="true" />
                </a>
                <h3>
                    <a href="#">Assignment Two</a>
                </h3>
            </div>
        </div>
        <div class="col-md-3 portfolio-item">
            <div class="thumbnail">
                <a href="#">
                    <img class="img-responsive" src="~/images/LIS3784/LIS3784_A3.png" alt="A3 LIS3784" style="height:150px" asp-append-version="true" />
                </a>
                <h3>
                    <a href="#">Assignment Three</a>
                </h3>
            </div>
        </div>
        <div class="col-md-3 portfolio-item">
            <div class="thumbnail">


                <a href="#">
                    <img class="img-responsive" src="~/images/LIS3784/LIS3784_A4.png" alt="LIS3784 A4" style="height:150px" asp-append-version="true" />
                </a>
                <h3>
                    <a href="#">Assignment Four</a>
                </h3>

            </div>
        </div>
        <div class="col-md-3 portfolio-item">
            <div class="thumbnail">


                <a href="#">
                    <img class="img-responsive" src="~/images/LIS3784/LIS3784_A5.png" alt="LIS3784 A5" style="height:150px" asp-append-version="true" />
                </a>
                <h3>
                    <a href="#">Assignment Five</a>
                </h3>

            </div>
        </div>
    </div>
</div>

    <hr>
    <div class="row">
        <div class="col-md-5 portfolio-item">
            <div class="thumbnail">

                <a href="~/images/LIS3784/LIS3784_P1.png">
                    <img class="img-responsive" src="~/images/LIS3784/LIS3784_P1A.png" style="height:300px" alt="P1-LIS3784" asp-append-version="true" />
                </a>
                <h3>
                    <a href="~/pdf/SQL/P1_SQL.pdf">Project One <small>SQL Statements</small> </a> <a asp-area="" asp-controller="Project" asp-action="LIS3784_1" class="btn btn-primary pull-right"> Read More</a>
                </h3>

            </div>
        </div>
        <div class="col-md-5 portfolio-item col-md-offset-1">
            <div class="thumbnail">

                <a href="~/images/LIS3784/LIS3784_P2.png">
                    <img class="img-responsive" src="~/images/LIS3784/LIS3784_P2A.png" style="height:300px" alt="P2-LIS3784" asp-append-version="true" />
                </a>
                <h3>
                    <a href="~/pdf/SQL/LIS3784_p2_cbh12e.pdf">Project Two <small>SQL Statements</small></a>
                    <a asp-area="" asp-controller="Project" asp-action="LIS3784_2" class="btn btn-primary pull-right"> Read More</a>
                </h3>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <h3><i class="fa fa-ship"></i> CruiseOne - Project Tallahassee</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-9 portfolio-item col-md-offset-1">
                <div class="thumbnail">

                    <a href="~/images/db_model.png">
                        <img class="img-responsive" src="~/images/db_model.png" style="height: auto; width: 100%;" alt="Project Tally" asp-append-version="true" />
                    </a>
                    <h3>
                        <a href="#">Booking File Storage Web Application</a>
                    </h3>

                </div>
            </div>
        </div>

    </div>

    <!-- Modals -->
    <div id="portfolio-modals">

        <!-- GreenData Modal -->
        <div id="greenData" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">GreenData Page</h4>
                    </div>
                    <div class="modal-body">
                        <p>
                            This project is what got myself interested in doing web development. This was a group assignment and the group was assignmed to create a website for a business called GreenData. I was responsible in the creation of the Customer Service Page. Futhermore,  I did various fixes to the other pages well after the assignment was due.
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times-circle"></i> Close</button>
                    </div>
                </div>

            </div>
        </div>


        <!-- NFHI Modal -->
        <div id="nfhi" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">North Florida Home Inspections</h4>
                    </div>
                    <div class="modal-body">
                        <p>
                            This was the final project for LIS4381. We were assigned to create a page for an Home Inspection Company located in Panama City. I was the team leader for this assignment, and I saw my potential in having a career in web development and the ability to manage a team doing IT Projects.
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times-circle"></i> Close</button>
                    </div>
                </div>

            </div>
        </div>
    </div>

Views/Home/Resume.cshtml
@{
    ViewBag.Title = "Resume";
}
<h2>@ViewBag.Title</h2>

<div class="text-right"> <a href="~/pdf/chargarther_resume.pdf" class="btn btn-primary"><i class="fa fa-download"></i> Download Resume</a></div>
<!-- PDF Button -->
<!-- Education -->
<div class="row">

    <h3><i class="fa fa-university"></i> Education</h3>
    <hr>

    <div class="col-md-6 col-xs-12 col-sm-12">
        <img class="img img-responsive pull-left" src="~/images/logo/fsu.png" alt="fsu logo" />
        <h4>
            <strong> Florida State University</strong> <br />  Main Campus
            <br /> Tallahassee, Florida
            <br /> January 2013 - December 2015
        </h4>
        Bachelor's in Science Degree
        <br />Information Technology
        <br /> Graduated: December 2015
    </div>

    <div class="col-md-6 col-xs-12 col-sm-12">
        <span class="hidden-xs hidden-sm">
            <img class="img img-responsive pull-right" src="~/images/logo/fscj.png" alt="fscj logo" />
        </span>
        <span class="visible-xs visible-sm">
            <img class="img img-responsive pull-left" src="~/images/logo/fscj.png" alt="fscj logo" />
        </span>
        <h4>
            <strong> Florida State College at Jacksonville</strong>
            <br />  South Campus
            <br />Jacksonville, Florida
            <br />August 2009 to December 2012
        </h4>
        Associates in Arts Degree
        <br /> General Education
        <br /> Graduated: December 2012
    </div>
</div>
<div class="row">
    <!-- Experience -->
    <div class="col-md-6">
        <h3><i class="fa fa-laptop"></i> Information Technology Experience</h3>
        <hr>
        <p>
            Recent college graduate with experience in web development and performing various computer repairs, software
            installation and hardware maintenance. Knowledge of numerous technical applications and programming languages. A
            motivated problem solver with an aptitude for innovation and solutions development. Communicative and personable
            professional who clearly and persuasively describes the benefits of various technologies and process improvements.
        </p>
    </div>

    <!-- Skills -->
    <h3> <i class="fa fa-code"></i> Technical Skills</h3>
    <hr>
    <div class="col-md-6">
        <ul>
            <li><b>Operating Systems:</b> Windows XP, 7, 8, 8.1, 10, Windows Server 2003, 2008, 2012, OS X and Linux</li>
            <li><b>Program Languages:</b> HTML, CSS, PHP , C#, ASP.NET, MVC ,JavaScript, AJAX and jQuery</li>
            <li><b>Frameworks: </b>WordPress, Laravel, Drupal and OctoberCMS </li>
            <li><b>Software and Protocols:</b> Microsoft SharePoint, Visual Studio, Adobe Photoshop, Microsoft Office, Active Directory, Account Management, Group Policy, TCP/IP, VLAN, SMTP, FTP, SFTP, SMB, FileZilla, PuTTY, Git, Apache, IIS, nginx </li>
            <li><b>Web Applications:</b> Google Analytics, Google AdSense, Amazon Web Service, Google Cloud Platform, Microsoft Azure </li>
        </ul>
    </div>
</div>

<div class="row">
    <!-- Work Experience -->
    <h3> <i class="fa fa-briefcase"></i> Professional Experience</h3>
    <hr>

    <div class="col-md-6">
        <div class="row">
            <!--<img class="img img-responsive pull-left" src="~/images/logo/wth.png" alt="wth logo" />-->
            <h4><strong>Information Technology Consultant</strong> <br /> <i> Dream Vacations</i> <br />  Ponte Vedra, Florida <br /> June 2016 to present</h4>
        </div>
        <ul>
            <li>Designed, created, coded and implemented a two-factor authentication based web application to make it easier for associates of the franchise to upload and retrieve records.</li>
            <li>Performed technical support, computer installation, system installation and performs routine maintenance.</li>
            <li>Extremely knowledgeable about cruise products and services across various market segments (i.e., luxury, premium, deluxe, mass-market, and niche)</li>
        </ul>
    </div>

    <div class="col-md-6">
        <div class="row">
            <img class="img img-responsive pull-left" src="~/images/logo/wth.png" alt="wth logo" />
            <h4><strong>Information Technology Intern</strong> <br /> <i> World Travel Holdings</i> <br />  Fort Lauderdale, Florida <br /> May 2015 to August 2015</h4>
        </div>
        <ul>
            <li>Offered valuable feedback to staff on how to improve and increase efficiency and performance in overhauling the website of the organization. </li>
            <li>Performed daily testing of the organization’s website to look for bugs in software throughout the overhaul process.</li>
            <li>Participated in weekly meetings with members of the Information Department to oversee how the entire department operates on a daily basis throughout the internship.</li>
        </ul>
    </div>
    <div class="col-md-6">
        <div class="row">
            <img class="img img-responsive pull-left" src="~/images/logo/pvwc.png" alt="pvwc logo" />
            <h4> <strong>Computer Service Technician</strong> <br /> <i> Ponte Vedra Wellness Center</i> <br /> Ponte Vedra Beach, Florida <br /> May 2011 to July 2011 </h4>
        </div>
        <ul>
            <li> Scanned patient medical records to facilitate the medical practice’s initiative to go paperless to meet the mandates by the Affordable Care Act.</li>
            <li> Played a key role performing computer repairs, computer installation, data backups, software installation, and routine maintenance.</li>
        </ul>
    </div>
</div>

Views/Project/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Project/LIS3784_1.cshtml
@using System.Security
@{
    ViewData["Title"] = "Project 1: LIS3784 Fall 2014";
}
<div class="row">
    <a href="#statements" class="btn btn-primary"><i class="fa fa-database"></i> Project One <small> SQL Statements</small></a>
    <br />
    <p> This was the first project for the database course, this will allow you to see how I have progressed.</p>

    <p>
        Project Objective: As the IT Director for Financial Accountants Inc., I was asked to create an online
        family finance database for clients who will record credits (income) as well as debits
        (expenses), in order to keep track of monthly/yearly budgets.
    </p>
    <div class="row">
        <div class="col-md-6">
            <ul>
                Business Rules:
                <li> A financial institution provides many types of *accounts.</li>
                <li> Many types of accounts are available at many financial institutions.</li>
                <li> Many accounts can be associated with many users.</li>
                <li> Many users can have many accounts, but must have at least one.</li>
                <li> Many transactions are processed from many accounts.</li>
                <li> However, each transaction is processed from a specific account.</li>
                <li> Many users make many transactions.</li>
                <li> However, each transaction is processed by only one user.</li>
                <li> A budget category is used in many transactions.</li>
                <li> However, each transaction can only use one budget category.</li>
            </ul>
        </div>
        <div class="col-md-6">
            <a href="~/images/LIS3784/LIS3784_P1.png">
                <img class="img-responsive img-thumbnail" src="~/images/LIS3784/LIS3784_P1A.png" style="height: 330px" alt="P1-LIS3784" />
            </a>
        </div>

    </div>
    <div class="col-md-7 col-md-offset-3">
        <p id="statements" style="margin: 12px auto 6px auto; font-family: Helvetica, Arial, Sans-serif; font-style: normal; font-variant: normal; font-weight: normal; font-size: 14px; line-height: normal; font-size-adjust: none; font-stretch: normal; -x-system-font: none; display: block;">
            <a title="View P1_SQL on Scribd" href="https://www.scribd.com/doc/288145739/P1-SQL" style="text-decoration: underline;">P1_SQL</a>
        </p><iframe class="scribd_iframe_embed" src="https://www.scribd.com/embeds/288145739/content?start_page=1&view_mode=scroll&show_recommendations=true" data-auto-height="false" data-aspect-ratio="undefined" scrolling="no" id="doc_9353" width="100%" height="600" frameborder="0"></iframe>
    </div>
</div>

Views/Project/LIS3784_2.cshtml
@{
    ViewData["Title"] = "Project 2: LIS3784 Fall 2014";
}
<div class="row">
    <a href="#statements" class="btn btn-primary"><i class="fa fa-database"></i> Project Two <small> SQL Statements</small></a>
    <p> This was the final project for the database course. At this point, the course moved from using MySQL to Microsoft SQL. I learned a lot from doing this assignment because unlike using MYSQL Workbench to generate the create and insert statements, this required me to do all of the database functions with the exception of the select statements and select insert statements manually for the first time.</p>
    <br />
    <div class="col-md-6">
        <ul>
            Business Rules:
            <li> A physician will prescribe one or more treatments.</li>
            <li> A treatment can be prescribed by one or more physicians.</li>
            <li> A patient can receive one or more treatments.</li>
            <li> A treatment can be prescribed to one or more patients.</li>
            <li> Each prescribed treatment on a specific date, can be prescribed by only one physician to one patient.</li>
            <li> A patient can have many medications. </li>
            <li> Many medications can be given to many patients. </li>
            <li> A prescription can be administered in one or more treatments.</li>
            <li> A treatment can include one or more prescriptions.</li>
        </ul>
    </div>
    <div class="col-md-6">

        <a href="~/images/LIS3784/LIS3784_P2.png">
            <img class="img-responsive img-thumbnail" src="~/images/LIS3784/LIS3784_P2.png" style="height:330px" alt="P2-LIS3784" />
        </a>


    </div>
    <div class="col-md-7 col-md-offset-3">
        <p id="statements" class="text-center" style="margin: 12px auto 6px auto; font-family: Helvetica, Arial, Sans-serif; font-style: normal; font-variant: normal; font-weight: normal; font-size: 14px; line-height: normal; font-size-adjust: none; font-stretch: normal; -x-system-font: none; display: block;">
            <a title="View LIS3784_p2_cbh12e on Scribd" href="https://www.scribd.com/doc/288145737/LIS3784-p2-cbh12e" style="text-decoration: underline;">LIS3784_p2_cbh12e</a>
        </p><iframe class="scribd_iframe_embed" src="https://www.scribd.com/embeds/288145737/content?start_page=1&view_mode=scroll&show_recommendations=true" data-auto-height="false" data-aspect-ratio="undefined" scrolling="no" id="doc_32098" width="100%" height="600" frameborder="0"></iframe>
    </div>
</div>